"use strict";

window.SENTENCE_HUNTER_QUESTIONS = [
  {
    id: "g001",
    difficulty: "starter",
    category: "agreement",
    segments: ["She", "don't", "like", "coffee."],
    errorIndex: 1,
    correctAnswer: "doesn't",
    choices: ["doesn't", "isn't", "hasn't"],
    correctSentence: "She doesn't like coffee.",
    explanation: "현재형에서 주어가 she이면 doesn't를 사용합니다."
  },
  {
    id: "g002",
    difficulty: "starter",
    category: "agreement",
    segments: ["He", "go", "to", "work", "by", "bus", "every", "day."],
    errorIndex: 1,
    correctAnswer: "goes",
    choices: ["goes", "going", "gone"],
    correctSentence: "He goes to work by bus every day.",
    explanation: "3인칭 단수 주어 he의 현재형 동사에는 -s가 붙습니다."
  },
  {
    id: "g003",
    difficulty: "starter",
    category: "agreement",
    segments: ["They", "is", "waiting", "outside."],
    errorIndex: 1,
    correctAnswer: "are",
    choices: ["are", "am", "has"],
    correctSentence: "They are waiting outside.",
    explanation: "복수 주어 they에는 are를 사용합니다."
  },
  {
    id: "g004",
    difficulty: "starter",
    category: "verb_form",
    segments: ["I", "am agree", "with", "you."],
    errorIndex: 1,
    correctAnswer: "agree",
    choices: ["agree", "agrees", "agreeing"],
    correctSentence: "I agree with you.",
    explanation: "agree는 이 문장에서 일반동사이므로 be동사 없이 사용합니다."
  },
  {
    id: "g005",
    difficulty: "starter",
    category: "tense",
    segments: ["We", "went", "to", "the", "park", "yesterday", "and", "play", "soccer."],
    errorIndex: 7,
    correctAnswer: "played",
    choices: ["played", "plays", "playing"],
    correctSentence: "We went to the park yesterday and played soccer.",
    explanation: "yesterday와 went에 맞춰 병렬 동사도 과거형 played가 필요합니다."
  },
  {
    id: "g006",
    difficulty: "starter",
    category: "noun_plural",
    segments: ["She", "has", "two", "childs."],
    errorIndex: 3,
    correctAnswer: "children.",
    choices: ["children.", "childes.", "childrens."],
    correctSentence: "She has two children.",
    explanation: "child의 불규칙 복수형은 children입니다."
  },
  {
    id: "g007",
    difficulty: "starter",
    category: "article",
    segments: ["He", "bought", "a", "umbrella", "at", "the", "store."],
    errorIndex: 2,
    correctAnswer: "an",
    choices: ["an", "one of", "many"],
    correctSentence: "He bought an umbrella at the store.",
    explanation: "umbrella는 모음 소리로 시작하므로 an을 사용합니다."
  },
  {
    id: "g008",
    difficulty: "starter",
    category: "preposition",
    segments: ["My", "brother", "is", "good", "in", "math."],
    errorIndex: 4,
    correctAnswer: "at",
    choices: ["at", "on", "for"],
    correctSentence: "My brother is good at math.",
    explanation: "‘~을 잘하다’는 be good at으로 표현합니다."
  },
  {
    id: "g009",
    difficulty: "starter",
    category: "quantifier",
    segments: ["There", "are", "much", "people", "in", "the", "lobby."],
    errorIndex: 2,
    correctAnswer: "many",
    choices: ["many", "much of", "a little"],
    correctSentence: "There are many people in the lobby.",
    explanation: "셀 수 있는 복수명사 people 앞에는 many를 사용합니다."
  },
  {
    id: "g010",
    difficulty: "starter",
    category: "comparison",
    segments: ["This", "bag", "is", "more cheaper", "than", "mine."],
    errorIndex: 3,
    correctAnswer: "cheaper",
    choices: ["cheaper", "the cheaper", "cheaply"],
    correctSentence: "This bag is cheaper than mine.",
    explanation: "cheaper 자체가 비교급이므로 more를 함께 쓰지 않습니다."
  },
  {
    id: "g011",
    difficulty: "starter",
    category: "verb_form",
    segments: ["I", "didn't", "saw", "your", "message."],
    errorIndex: 2,
    correctAnswer: "see",
    choices: ["see", "seen", "seeing"],
    correctSentence: "I didn't see your message.",
    explanation: "조동사 did 뒤에는 동사원형 see가 옵니다."
  },
  {
    id: "g012",
    difficulty: "starter",
    category: "modal",
    segments: ["She", "can", "sings", "very", "well."],
    errorIndex: 2,
    correctAnswer: "sing",
    choices: ["sing", "sang", "singing"],
    correctSentence: "She can sing very well.",
    explanation: "조동사 can 뒤에는 동사원형을 사용합니다."
  },
  {
    id: "g013",
    difficulty: "everyday",
    category: "preposition",
    segments: ["I", "have", "lived", "here", "since", "five", "years."],
    errorIndex: 4,
    correctAnswer: "for",
    choices: ["for", "during", "from"],
    correctSentence: "I have lived here for five years.",
    explanation: "기간에는 for, 시작 시점에는 since를 사용합니다."
  },
  {
    id: "g014",
    difficulty: "everyday",
    category: "preposition",
    segments: ["He", "is", "married", "with", "a", "doctor."],
    errorIndex: 3,
    correctAnswer: "to",
    choices: ["to", "by", "at"],
    correctSentence: "He is married to a doctor.",
    explanation: "‘~와 결혼한’은 be married to로 표현합니다."
  },
  {
    id: "g015",
    difficulty: "everyday",
    category: "verb_pattern",
    segments: ["We", "discussed about", "the", "problem", "for", "an", "hour."],
    errorIndex: 1,
    correctAnswer: "discussed",
    choices: ["discussed", "discussing", "were discussed"],
    correctSentence: "We discussed the problem for an hour.",
    explanation: "discuss는 타동사이므로 목적어 앞에 about을 쓰지 않습니다."
  },
  {
    id: "g016",
    difficulty: "everyday",
    category: "verb_pattern",
    segments: ["She", "suggested", "to go", "home", "early."],
    errorIndex: 2,
    correctAnswer: "going",
    choices: ["going", "goes", "went"],
    correctSentence: "She suggested going home early.",
    explanation: "suggest 뒤에는 동명사 형태를 사용할 수 있습니다."
  },
  {
    id: "g017",
    difficulty: "everyday",
    category: "verb_pattern",
    segments: ["I", "look", "forward", "to", "meet", "you", "next", "week."],
    errorIndex: 4,
    correctAnswer: "meeting",
    choices: ["meeting", "met", "have met"],
    correctSentence: "I look forward to meeting you next week.",
    explanation: "look forward to에서 to는 전치사이므로 동명사가 옵니다."
  },
  {
    id: "g018",
    difficulty: "everyday",
    category: "agreement",
    segments: ["The", "news", "are", "surprising."],
    errorIndex: 2,
    correctAnswer: "is",
    choices: ["is", "be", "has"],
    correctSentence: "The news is surprising.",
    explanation: "news는 형태는 -s지만 단수 취급합니다."
  },
  {
    id: "g019",
    difficulty: "everyday",
    category: "agreement",
    segments: ["Each", "of", "the", "boxes", "contain", "a", "gift."],
    errorIndex: 4,
    correctAnswer: "contains",
    choices: ["contains", "containing", "have contained"],
    correctSentence: "Each of the boxes contains a gift.",
    explanation: "주어의 핵심인 each는 단수이므로 contains가 필요합니다."
  },
  {
    id: "g020",
    difficulty: "everyday",
    category: "word_order",
    segments: ["She", "asked", "me", "where", "was I going."],
    errorIndex: 4,
    correctAnswer: "I was going.",
    choices: ["I was going.", "was going I.", "I am go."],
    correctSentence: "She asked me where I was going.",
    explanation: "간접의문문은 의문사 뒤에 주어+동사 어순을 사용합니다."
  },
  {
    id: "g021",
    difficulty: "everyday",
    category: "conditionals",
    segments: ["If", "I", "will see", "him,", "I'll", "tell", "him."],
    errorIndex: 2,
    correctAnswer: "see",
    choices: ["see", "saw", "would see"],
    correctSentence: "If I see him, I'll tell him.",
    explanation: "첫 번째 조건문에서 if절에는 현재형을 사용합니다."
  },
  {
    id: "g022",
    difficulty: "everyday",
    category: "tense",
    segments: ["I", "have been", "to", "Paris", "last", "year."],
    errorIndex: 1,
    correctAnswer: "went",
    choices: ["went", "have gone", "was go"],
    correctSentence: "I went to Paris last year.",
    explanation: "last year처럼 끝난 과거 시점에는 단순과거를 사용합니다."
  },
  {
    id: "g023",
    difficulty: "everyday",
    category: "verb_pattern",
    segments: ["He", "explained me the rule", "twice."],
    errorIndex: 1,
    correctAnswer: "explained the rule to me",
    choices: ["explained the rule to me", "said me the rule", "explained me about the rule"],
    correctSentence: "He explained the rule to me twice.",
    explanation: "explain은 explain something to someone의 구조를 사용합니다."
  },
  {
    id: "g024",
    difficulty: "everyday",
    category: "quantifier",
    segments: ["There", "is", "fewer", "traffic", "today."],
    errorIndex: 2,
    correctAnswer: "less",
    choices: ["less", "few", "many"],
    correctSentence: "There is less traffic today.",
    explanation: "traffic은 셀 수 없는 명사이므로 less를 사용합니다."
  },
  {
    id: "g025",
    difficulty: "challenger",
    category: "agreement",
    segments: ["Each", "of", "the", "proposals,", "along", "with", "its", "supporting", "documents,", "have", "been", "reviewed."],
    errorIndex: 9,
    correctAnswer: "has",
    choices: ["has", "having", "were"],
    correctSentence: "Each of the proposals, along with its supporting documents, has been reviewed.",
    explanation: "along with 이하와 관계없이 핵심 주어 each에 맞춰 has를 씁니다."
  },
  {
    id: "g026",
    difficulty: "challenger",
    category: "agreement",
    segments: ["The", "number", "of", "applicants", "have", "increased", "this", "year."],
    errorIndex: 4,
    correctAnswer: "has",
    choices: ["has", "having", "are"],
    correctSentence: "The number of applicants has increased this year.",
    explanation: "the number of는 ‘그 수’라는 단수 주어이므로 has가 필요합니다."
  },
  {
    id: "g027",
    difficulty: "challenger",
    category: "inversion",
    segments: ["Hardly", "I had", "arrived", "when", "the", "meeting", "began."],
    errorIndex: 1,
    correctAnswer: "had I",
    choices: ["had I", "I have", "did I"],
    correctSentence: "Hardly had I arrived when the meeting began.",
    explanation: "부정 의미의 Hardly가 문두에 오면 조동사와 주어가 도치됩니다."
  },
  {
    id: "g028",
    difficulty: "challenger",
    category: "subjunctive",
    segments: ["The", "manager", "demanded", "that", "he", "attends", "the", "meeting."],
    errorIndex: 5,
    correctAnswer: "attend",
    choices: ["attend", "attended", "attending"],
    correctSentence: "The manager demanded that he attend the meeting.",
    explanation: "demand 뒤 that절에서는 주어와 관계없이 동사원형을 사용합니다."
  },
  {
    id: "g029",
    difficulty: "challenger",
    category: "inversion",
    segments: ["Not", "only", "she speaks", "French,", "but", "she", "also", "writes", "it", "fluently."],
    errorIndex: 2,
    correctAnswer: "does she speak",
    choices: ["does she speak", "she does speak", "did she spoke"],
    correctSentence: "Not only does she speak French, but she also writes it fluently.",
    explanation: "Not only가 문두에 오면 첫 절은 의문문과 같은 도치 어순을 취합니다."
  },
  {
    id: "g030",
    difficulty: "challenger",
    category: "perfect_tense",
    segments: ["By", "the", "time", "we", "arrived,", "the", "movie", "already started."],
    errorIndex: 7,
    correctAnswer: "had already started.",
    choices: ["had already started.", "has already started.", "was already start."],
    correctSentence: "By the time we arrived, the movie had already started.",
    explanation: "도착보다 영화 시작이 먼저이므로 과거완료를 사용합니다."
  }
];
